apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-modules
  namespace: kube-system
  labels:
    k8s-app: metricbeat
data:
  # This module requires `kube-state-metrics` up and running under `kube-system` namespace
  kubernetes.yml: |-
    - module: kubernetes
      metricsets:
        - state_node
        - state_deployment
        - state_replicaset
        - state_pod
        - state_container
        # Uncomment this to get k8s events:
        - event
      period: 10s
      host: ${NODE_NAME}
      hosts: ["kube-state-metrics:8080"]
  
#  aws.yml: |-
#    - module: aws
#      period: 300s
#      metricsets:
#        - ec2
#        - ebs
#        - cloudwatch
#        - elb
#        - rds
#        - s3_daily_storage
#        - s3_request
#        - sqs
#      metrics:
#        - namespace: AWS/EBS
#        - namespace: AWS/ELB
#        - namespace: AWS/EC2
#      access_key_id: ${AWS_ACCESS_KEY_ID}
#      secret_access_key: ${AWS_SECRET_ACCESS_KEY}
