apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricbeat
  namespace: kube-system
  labels:
    k8s-app: metricbeat
spec:
  selector:
    matchLabels:
      k8s-app: metricbeat
  template:
    metadata:
      labels:
        k8s-app: metricbeat
    spec:
      serviceAccountName: metricbeat
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:7.9.2
        args: [
          "-c", "/usr/share/metricbeat/metricbeat.yml",
          "-e",
          "-system.hostfs=/hostfs"
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: "<insert elasticsearch host ip>"
        - name: ELASTICSEARCH_PORT
          value: "<insert elasticsearch host port>"
        - name: ELASTICSEARCH_USERNAME
          value: "<insert elasticsearch username>"
        - name: ELASTICSEARCH_PASSWORD
          value: "<insert elasticsearch password>"
        - name: AWS_ACCESS_KEY_ID
          value: "<insert AWS access key ID>"
        - name: AWS_SECRET_ACCESS_KEY
          value: "<insert AWS secret access key>"
        - name: KIBANA_ADDRESS
          value: "<insert kibana address>"
        - name: KIBANA_PORT
          value: "<insert kibana port>"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /usr/share/metricbeat/metricbeat.yml
          readOnly: true
          subPath: metricbeat.yml
        - name: modules
          mountPath: /usr/share/metricbeat/modules.d
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: metricbeat-deployment-config
      - name: modules
        configMap:
          defaultMode: 0600
          name: metricbeat-deployment-modules
