apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-config
  namespace: kube-system
  labels:
    k8s-app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      # Mounted `metricbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: false

    setup.template.settings:
      index.number_of_shards: 1
      index.number_of_replicas: 0
      index.codec: best_compression

    setup.template.name: "metricbeat"
    setup.template.pattern: "metricbeat-*"

    path.home: /usr/share/metricbeat
    path.bin: /usr/share/metricbeat
    path.config: /usr/share/metricbeat
    path.data: /usr/share/metricbeat/data
    path.logs: /usr/share/metricbeat/logs

    setup.dashboards.enabled: true
    setup.dashboards.index: "metricbeat-*"
    setup.dashboards.directory: /usr/share/metricbeat/kibana/

    setup.kibana:
      host: "${KIBANA_ADDRESS}:${KIBANA_PORT}"
      ssl.verification_mode: none


    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}']
      username: "${ELASTICSEARCH_USERNAME}"
      password: "${ELASTICSEARCH_PASSWORD}"
      index: "metricbeat"

    processors:
      - add_cloud_metadata:
      - add_fields:
          labels:
            squad: ${SQUAD_ID}
            env: ${ENV_ID}
