apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-setup-config
  namespace: kube-system
  labels:
    k8s-app: metricbeat
    kubernetes.io/cluster-service: "true"
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false
    setup.template.settings:
      index.number_of_shard: 1
      index.codec: best_compression
    space.id: <insert space_id>
    #cloud.auth ${ELASTIC_CLOUD_AUTH}
    #cloud.id ${ELASTIC_CLOUD_ID}
    setup.kibana.host: "<insert kibana host_ip>"
    setup.kibana.username: ${ELASTICSEARCH_USERNAME}
    setup.kibana.password ${ELASTICSEARCH_PASSWORD}
    path.home: /usr/share/metricbeat
    path.bin: /usr/share/metricbeat
    path.config: /usr/share/metricbeat/
    setup.dashboards.enabled: true
    setup.dashboards.index: "metricbeat-*"
    setup.dashboards.directory: /usr/share/metricbeat/kibana/
    
